before:
  hooks:
    - go mod download
builds:
- env:
  - CGO_ENABLED=0
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
brews:
  - github:
      owner: Jefferson-Faseler
      name: homebrew-prion
    folder: Formula
    homepage: https://github.com/Jefferson-Faseler/prion
    dependencies:
      - git
    description: A vim package manager, designed foor use with pathogen
    test: |
      system "#{bin}/prion -v"
